Resolve issue fossasia#1939
fossasia/open-event-organizer-android pull request #1959
Opened 2019-10-08 19:47 UTC by tusharr-98

Fixes #1939 

Changes: At the time of signup, the Last name field is optional, so if we don't fill this field then it shows the last name as null in navigation drawer as there was no check on the last name to be null. I have added a check on the user's last name to be "" if null otherwise the last name entered by the user.

Screenshots for the change:
![Screenshot_20191009-011540](https://user-images.githubusercontent.com/48120319/66427855-77c25680-ea32-11e9-89d8-e3e87c63ff70.png)

2019-10-08 19:49 UTC, ShridharGoel approved these changes

2019-10-08 20:34 UTC, iamareebjamal requested changes
Change PR title according to the guidelines

2019-10-10 03:41 UTC, tusharr-98 commented
@iamareebjamal  I have changed the PR title accordingly.

2019-10-10 04:30 UTC, iamareebjamal approved these changes

2019-10-10 04:30 UTC, merged