solved mutiple toast message error
fossasia/open-event-organizer-android pull request #1982
Opened 2019-11-26 14:28 UTC by rishabh-997

Fixes #1981 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 
I made a function to empty the string after a toast message is displayed as the onError variable was not updated after removal of error and it was observed and displayed every time the activity started again. I also checked for empty messages and did not displayed them if they were null.
- [change 1](https://github.com/fossasia/open-event-organizer-android/compare/development...rishabh-997:develop?expand=1#diff-ef13da30f7163ed5cfe918e02b09ecb1)
- [change 2](https://github.com/fossasia/open-event-organizer-android/compare/development...rishabh-997:develop?expand=1#diff-ccd9f34b0b9f443f63acbf0a4e442e09)

2019-11-26 14:32 UTC, iamareebjamal commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/open-event-orga-app/open-event-orga-app/pullRequest?prid=4568976&bid=15359573)

2019-11-26 14:32 UTC, iamareebjamal commented on app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java
> +        if(!message.equals("")){
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Position literals first in String comparisons](https://app.codacy.com/app/fossasia/open-event-orga-app/pullRequest?prid=4568976)

2019-11-26 14:32 UTC, iamareebjamal commented on app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java
> +        if(!error.equals("")) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Position literals first in String comparisons](https://app.codacy.com/app/fossasia/open-event-orga-app/pullRequest?prid=4568976)

2019-11-26 15:13 UTC, iamareebjamal requested changes
It's a workaround. Not a fix

2019-11-26 15:28 UTC, rishabh-997 commented
> It's a workaround. Not a fix

sir, the problem was that the error was not being updated after being resolved. What changes will you suggest?

2019-11-29 18:58 UTC, iamareebjamal commented on app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java
> -
revert

2019-11-29 18:58 UTC, iamareebjamal commented on app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java
> -
revert

2019-11-29 19:18 UTC, iamareebjamal approved these changes

2019-11-29 19:19 UTC, merged