fix: Button disappear on orientation change
fossasia/open-event-organizer-android pull request #2062
Opened 2020-01-28 20:23 UTC by dheerajkotwani

Fixes #2059 Precious button disappear on orientation change

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes::
Restricted the activity from calling onCreate when the orientation on device is changed while creating any event.

Screenshots for the change:
![fix_orientation](https://user-images.githubusercontent.com/44086235/73302106-12d97900-423a-11ea-8027-ed419cb0c56b.gif)

2020-01-28 20:24 UTC, iamareebjamal requested changes
Wrong

2020-01-28 20:26 UTC, iamareebjamal commented
> Precious button disappear on orientation change

![](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fgifimage.net%2Fwp-content%2Fuploads%2F2017%2F11%2Fgollum-my-precious-gif-10.gif&f=1&nofb=1)

2020-01-29 06:54 UTC, iamareebjamal commented
This is not fixing the bug of button disappearing

2020-01-29 11:57 UTC, dheerajkotwani commented
@iamareebjamal it worked with the devices I tested

2020-01-29 12:08 UTC, iamareebjamal commented
Of course it worked. You turned off rotations

2020-01-29 12:12 UTC, dheerajkotwani commented
Rotations are turned turned on you can see the gif I had attached

2020-01-29 12:13 UTC, iamareebjamal commented
It turned off the relayouting on config changes which is not what we want

2020-01-29 12:21 UTC, dheerajkotwani commented
can you help with some approach, I tried various method but only this worked for me

2020-01-29 12:38 UTC, iamareebjamal commented
First you need to find out why it is breaking

2020-01-29 12:54 UTC, dheerajkotwani commented
when the orientation of the device got changed the onCreate method is called again, and it sets the value of position of the indicator and pager to 0 and goes to onScrollChangeListener which makes the previous button disappear when its position is 0 but the actual value of it is 1 and the button should not get disappeared.

2020-01-29 13:19 UTC, iamareebjamal commented
Then change to ex[ected position in onCreate

2020-01-29 13:28 UTC, dheerajkotwani commented
trying with another approach, saving its visibility in onSaveInstanceState, lets try if this works

2020-01-29 14:12 UTC, iamareebjamal commented on app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventActivity.java
> +import android.widget.Toast;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'android.widget.Toast'](https://app.codacy.com/manual/fossasia/open-event-orga-app/pullRequest?prid=4903246)

2020-01-29 14:12 UTC, iamareebjamal commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-orga-app/pullRequest?prid=4903246&bid=16235790)

2023-04-29 12:24 UTC, closed without merging